// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAj8aW57AHNWiQ8YJ4YJhT9-KUxrO5pSE',
    appId: '1:235980589398:android:618e4a478d76a38ab16ef7',
    messagingSenderId: '235980589398',
    projectId: 'digikhata-616f4',
    storageBucket: 'digikhata-616f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKN53NbuWogqLIjpv44ldivTK0DQXBJTY',
    appId: '1:235980589398:ios:78215d189f05155ab16ef7',
    messagingSenderId: '235980589398',
    projectId: 'digikhata-616f4',
    storageBucket: 'digikhata-616f4.appspot.com',
    androidClientId: '235980589398-572eb39vm9jfkmt8iic4t404ghqc43n8.apps.googleusercontent.com',
    iosClientId: '235980589398-v1qgiufs6n6smv9eq64i7294pic5tfn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.digiKhata',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcu0GBRhWe6whFfPUHU6rT8NhuWBP76Tw',
    appId: '1:235980589398:web:4e4dc8561317e93fb16ef7',
    messagingSenderId: '235980589398',
    projectId: 'digikhata-616f4',
    authDomain: 'digikhata-616f4.firebaseapp.com',
    storageBucket: 'digikhata-616f4.appspot.com',
    measurementId: 'G-0RDPHP9FXS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKN53NbuWogqLIjpv44ldivTK0DQXBJTY',
    appId: '1:235980589398:ios:78215d189f05155ab16ef7',
    messagingSenderId: '235980589398',
    projectId: 'digikhata-616f4',
    storageBucket: 'digikhata-616f4.appspot.com',
    androidClientId: '235980589398-572eb39vm9jfkmt8iic4t404ghqc43n8.apps.googleusercontent.com',
    iosClientId: '235980589398-v1qgiufs6n6smv9eq64i7294pic5tfn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.digiKhata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcu0GBRhWe6whFfPUHU6rT8NhuWBP76Tw',
    appId: '1:235980589398:web:65da21c93e702e77b16ef7',
    messagingSenderId: '235980589398',
    projectId: 'digikhata-616f4',
    authDomain: 'digikhata-616f4.firebaseapp.com',
    storageBucket: 'digikhata-616f4.appspot.com',
    measurementId: 'G-6SWT8FP556',
  );

}